# Generated by Django 4.1.1 on 2022-09-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursemodel',
            table='course',
        ),
    ]
