# Generated by Django 4.1.1 on 2022-09-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursemodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
